"""PostgreSQL persistence API."""

from geonexa_proxima.db.base import Base
from geonexa_proxima.db.repository import (
    ItemNotFoundError,
    SQLAlchemyItemRepository,
    normalize_arxiv_id,
    normalize_doi,
    normalize_title,
)
from geonexa_proxima.db.session import (
    SessionFactory,
    create_engine,
    create_session_factory,
    init_database,
    session_scope,
)
from geonexa_proxima.db.subscriber_repository import (
    CHAT_KINDS,
    PERSONAL_KINDS,
    PRESENT_BOT_STATUSES,
    ChatIdentity,
    ChatRecord,
    KindBreakdown,
    PlanLimits,
    PlanNotFoundError,
    SubscriberNotFoundError,
    SubscriberRepository,
    SubscriptionNotFoundError,
    SubscriptionOverlapError,
    SubscriptionRecord,
    kind_from_chat_type,
)
from geonexa_proxima.db.user_repository import (
    FinalProfileDeletionError,
    InterestNotFoundError,
    ProfileNotFoundError,
    SQLAlchemyUserProfileRepository,
    UserNotFoundError,
    normalize_profile_name,
)

__all__ = [
    "CHAT_KINDS",
    "PERSONAL_KINDS",
    "PRESENT_BOT_STATUSES",
    "Base",
    "ChatIdentity",
    "ChatRecord",
    "FinalProfileDeletionError",
    "InterestNotFoundError",
    "ItemNotFoundError",
    "KindBreakdown",
    "PlanLimits",
    "PlanNotFoundError",
    "ProfileNotFoundError",
    "SQLAlchemyItemRepository",
    "SQLAlchemyUserProfileRepository",
    "SessionFactory",
    "SubscriberNotFoundError",
    "SubscriberRepository",
    "SubscriptionNotFoundError",
    "SubscriptionOverlapError",
    "SubscriptionRecord",
    "UserNotFoundError",
    "create_engine",
    "create_session_factory",
    "init_database",
    "kind_from_chat_type",
    "normalize_arxiv_id",
    "normalize_doi",
    "normalize_profile_name",
    "normalize_title",
    "session_scope",
]
